In [1]:
import pandas as pd
import numpy as np

In [37]:
df = pd.read_csv('GA_features.csv')
df

,Unnamed: 0.1,Unnamed: 0,county,tweets,contribution,n_poll,frac_unem,frac_votes,total_votes,registered_A_a,...,frac_voted_A,frac_voted_B,frac_voted_C,frac_voted_D,voted_E.1,frac_voted_F,frac_voted_G,total_registers,latitude,longitude
0,0,0,APPLING,0,235818,0,0.160193,0.695728,8403,967,...,0.155540,0.783292,0.004165,0.012972,0.001071,0.004046,0.038915,12078,31.7492,-82.2889
1,1,1,ATKINSON,0,93026,0,0.117003,0.649241,3167,400,...,0.187243,0.729081,0.000947,0.050837,0.000947,0.003789,0.027155,4878,31.2971,-82.8800
2,2,2,BACON,0,173074,0,0.115665,0.672325,4674,340,...,0.085794,0.858151,0.002353,0.010270,0.000642,0.003637,0.039153,6952,31.5537,-82.4527
3,3,3,BAKER,0,72226,0,0.179682,0.682852,1561,412,...,0.383088,0.570788,0.006406,0.006406,0.001281,0.002562,0.029468,2286,31.3262,-84.4447
4,4,4,BALDWIN,2,927608,0,0.173954,0.673200,18342,4601,...,0.374932,0.572239,0.008123,0.007796,0.000872,0.005670,0.030367,27246,33.0693,-83.2496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,154,154,WHITFIELD,0,4216384,1,0.070532,0.660559,36955,1040,...,0.034745,0.749127,0.009552,0.127588,0.001380,0.009796,0.067812,55945,34.8056,-84.9672
155,155,155,WILCOX,0,101176,0,0.182849,0.690566,3294,570,...,0.230419,0.740437,0.002429,0.007286,0.000607,0.003643,0.015179,4770,31.9729,-83.4323
156,156,156,WILKES,0,142526,0,0.206583,0.703740,5024,1147,...,0.344944,0.605494,0.004976,0.004379,0.001393,0.005772,0.033041,7139,33.7819,-82.7432
157,157,157,WILKINSON,0,92444,0,0.163246,0.711561,4776,1151,...,0.383585,0.581449,0.001675,0.002094,0.001466,0.003769,0.025963,6712,32.8024,-83.1712
158,158,158,WORTH,0,230358,0,0.114777,0.645210,9322,1555,...,0.212186,0.746514,0.002145,0.004398,0.000536,0.005149,0.029071,14448,31.5515,-83.8509

In [21]:
# Calculate the mean of the 'n_poll' column
mean_value = df['n_poll'].mean()

# Update the column based on the condition
df['n_poll'] = df['n_poll'].apply(lambda x: 0 if x < mean_value else 1)

# View the updated DataFrame
df

,Unnamed: 0,county,tweets,contribution,n_poll,fr_unem,fr_votes,total_votes,registered_A_a,registered_A_b,...,voted_A.1,voted_B.1,voted_C.1,voted_D.1,voted_E.1,voted_F.1,voted_G.1,total_registers,latitude,longitude
0,0,APPLING,0,235818,0,0.160193,0.695728,8403,967,1195,...,0.155540,0.783292,0.004165,0.012972,0.001071,0.004046,0.038915,12078,31.7492,-82.2889
1,1,ATKINSON,0,93026,0,0.117003,0.649241,3167,400,512,...,0.187243,0.729081,0.000947,0.050837,0.000947,0.003789,0.027155,4878,31.2971,-82.8800
2,2,BACON,0,173074,0,0.115665,0.672325,4674,340,559,...,0.085794,0.858151,0.002353,0.010270,0.000642,0.003637,0.039153,6952,31.5537,-82.4527
3,3,BAKER,0,72226,0,0.179682,0.682852,1561,412,517,...,0.383088,0.570788,0.006406,0.006406,0.001281,0.002562,0.029468,2286,31.3262,-84.4447
4,4,BALDWIN,2,927608,0,0.173954,0.673200,18342,4601,6382,...,0.374932,0.572239,0.008123,0.007796,0.000872,0.005670,0.030367,27246,33.0693,-83.2496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,154,WHITFIELD,0,4216384,1,0.070532,0.660559,36955,1040,1159,...,0.034745,0.749127,0.009552,0.127588,0.001380,0.009796,0.067812,55945,34.8056,-84.9672
155,155,WILCOX,0,101176,0,0.182849,0.690566,3294,570,748,...,0.230419,0.740437,0.002429,0.007286,0.000607,0.003643,0.015179,4770,31.9729,-83.4323
156,156,WILKES,0,142526,0,0.206583,0.703740,5024,1147,1529,...,0.344944,0.605494,0.004976,0.004379,0.001393,0.005772,0.033041,7139,33.7819,-82.7432
157,157,WILKINSON,0,92444,0,0.163246,0.711561,4776,1151,1456,...,0.383585,0.581449,0.001675,0.002094,0.001466,0.003769,0.025963,6712,32.8024,-83.1712
158,158,WORTH,0,230358,0,0.114777,0.645210,9322,1555,2004,...,0.212186,0.746514,0.002145,0.004398,0.000536,0.005149,0.029071,14448,31.5515,-83.8509

In [24]:
df.columns

Index(['Unnamed: 0', 'county', 'tweets', 'contribution', 'n_poll', 'fr_unem',
       'fr_votes', 'total_votes', 'registered_A_a', 'registered_A_b',
       ...
       'voted_A.1', 'voted_B.1', 'voted_C.1', 'voted_D.1', 'voted_E.1',
       'voted_F.1', 'voted_G.1', 'total_registers', 'latitude', 'longitude'],
      dtype='object', length=123)

In [38]:
# Identify columns where all values are between 0 and 1, exclude 'county', and check if not already prefixed with 'frac_'
columns_to_rename = [
    col for col in df.columns 
    if col != 'county' and not col.startswith('frac_') 
    and (df[col].astype(float) >= 0).all() 
    and (df[col].astype(float) < 1).all()
]

# Rename the columns
df.rename(columns={col: f'frac_{col}' for col in columns_to_rename}, inplace=True)

# View the updated DataFrame
print(df)

     Unnamed: 0.1  Unnamed: 0     county  tweets  contribution  n_poll  \
0               0           0    APPLING       0        235818       0
1               1           1   ATKINSON       0         93026       0
2               2           2      BACON       0        173074       0
3               3           3      BAKER       0         72226       0
4               4           4    BALDWIN       2        927608       0
..            ...         ...        ...     ...           ...     ...
154           154         154  WHITFIELD       0       4216384       1
155           155         155     WILCOX       0        101176       0
156           156         156     WILKES       0        142526       0
157           157         157  WILKINSON       0         92444       0
158           158         158      WORTH       0        230358       0

     frac_unem  frac_votes  total_votes  registered_A_a  ...  frac_voted_A  \
0     0.160193    0.695728         8403             967  ...      0.155540
1     0.117003    0.649241         3167             400  ...      0.187243
2     0.115665    0.672325         4674             340  ...      0.085794
3     0.179682    0.682852         1561             412  ...      0.383088
4     0.173954    0.673200        18342            4601  ...      0.374932
..         ...         ...          ...             ...  ...           ...
154   0.070532    0.660559        36955            1040  ...      0.034745
155   0.182849    0.690566         3294             570  ...      0.230419
156   0.206583    0.703740         5024            1147  ...      0.344944
157   0.163246    0.711561         4776            1151  ...      0.383585
158   0.114777    0.645210         9322            1555  ...      0.212186

     frac_voted_B  frac_voted_C  frac_voted_D  frac_voted_E.1  frac_voted_F  \
0        0.783292      0.004165      0.012972        0.001071      0.004046
1        0.729081      0.000947      0.050837        0.000947      0.003789
2        0.858151      0.002353      0.010270        0.000642      0.003637
3        0.570788      0.006406      0.006406        0.001281      0.002562
4        0.572239      0.008123      0.007796        0.000872      0.005670
..            ...           ...           ...             ...           ...
154      0.749127      0.009552      0.127588        0.001380      0.009796
155      0.740437      0.002429      0.007286        0.000607      0.003643
156      0.605494      0.004976      0.004379        0.001393      0.005772
157      0.581449      0.001675      0.002094        0.001466      0.003769
158      0.746514      0.002145      0.004398        0.000536      0.005149

     frac_voted_G  total_registers  latitude  longitude
0        0.038915            12078   31.7492   -82.2889
1        0.027155             4878   31.2971   -82.8800
2        0.039153             6952   31.5537   -82.4527
3        0.029468             2286   31.3262   -84.4447
4        0.030367            27246   33.0693   -83.2496
..            ...              ...       ...        ...
154      0.067812            55945   34.8056   -84.9672
155      0.015179             4770   31.9729   -83.4323
156      0.033041             7139   33.7819   -82.7432
157      0.025963             6712   32.8024   -83.1712
158      0.029071            14448   31.5515   -83.8509

[159 rows x 124 columns]

In [41]:
# Remove '.1' from all column names
df.columns = df.columns.str.replace('.1', '', regex=False)

df

,Unnamed: 0,Unnamed: 0,county,tweets,contribution,n_poll,frac_unem,frac_votes,total_votes,registered_A_a,...,frac_voted_A,frac_voted_B,frac_voted_C,frac_voted_D,frac_voted_E,frac_voted_F,frac_voted_G,total_registers,latitude,longitude
0,0,0,APPLING,0,235818,0,0.160193,0.695728,8403,967,...,0.155540,0.783292,0.004165,0.012972,0.001071,0.004046,0.038915,12078,31.7492,-82.2889
1,1,1,ATKINSON,0,93026,0,0.117003,0.649241,3167,400,...,0.187243,0.729081,0.000947,0.050837,0.000947,0.003789,0.027155,4878,31.2971,-82.8800
2,2,2,BACON,0,173074,0,0.115665,0.672325,4674,340,...,0.085794,0.858151,0.002353,0.010270,0.000642,0.003637,0.039153,6952,31.5537,-82.4527
3,3,3,BAKER,0,72226,0,0.179682,0.682852,1561,412,...,0.383088,0.570788,0.006406,0.006406,0.001281,0.002562,0.029468,2286,31.3262,-84.4447
4,4,4,BALDWIN,2,927608,0,0.173954,0.673200,18342,4601,...,0.374932,0.572239,0.008123,0.007796,0.000872,0.005670,0.030367,27246,33.0693,-83.2496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,154,154,WHITFIELD,0,4216384,1,0.070532,0.660559,36955,1040,...,0.034745,0.749127,0.009552,0.127588,0.001380,0.009796,0.067812,55945,34.8056,-84.9672
155,155,155,WILCOX,0,101176,0,0.182849,0.690566,3294,570,...,0.230419,0.740437,0.002429,0.007286,0.000607,0.003643,0.015179,4770,31.9729,-83.4323
156,156,156,WILKES,0,142526,0,0.206583,0.703740,5024,1147,...,0.344944,0.605494,0.004976,0.004379,0.001393,0.005772,0.033041,7139,33.7819,-82.7432
157,157,157,WILKINSON,0,92444,0,0.163246,0.711561,4776,1151,...,0.383585,0.581449,0.001675,0.002094,0.001466,0.003769,0.025963,6712,32.8024,-83.1712
158,158,158,WORTH,0,230358,0,0.114777,0.645210,9322,1555,...,0.212186,0.746514,0.002145,0.004398,0.000536,0.005149,0.029071,14448,31.5515,-83.8509

In [42]:
df.to_csv('GA_features.csv')

In [43]:
df

,Unnamed: 0,Unnamed: 0,county,tweets,contribution,n_poll,frac_unem,frac_votes,total_votes,registered_A_a,...,frac_voted_A,frac_voted_B,frac_voted_C,frac_voted_D,frac_voted_E,frac_voted_F,frac_voted_G,total_registers,latitude,longitude
0,0,0,APPLING,0,235818,0,0.160193,0.695728,8403,967,...,0.155540,0.783292,0.004165,0.012972,0.001071,0.004046,0.038915,12078,31.7492,-82.2889
1,1,1,ATKINSON,0,93026,0,0.117003,0.649241,3167,400,...,0.187243,0.729081,0.000947,0.050837,0.000947,0.003789,0.027155,4878,31.2971,-82.8800
2,2,2,BACON,0,173074,0,0.115665,0.672325,4674,340,...,0.085794,0.858151,0.002353,0.010270,0.000642,0.003637,0.039153,6952,31.5537,-82.4527
3,3,3,BAKER,0,72226,0,0.179682,0.682852,1561,412,...,0.383088,0.570788,0.006406,0.006406,0.001281,0.002562,0.029468,2286,31.3262,-84.4447
4,4,4,BALDWIN,2,927608,0,0.173954,0.673200,18342,4601,...,0.374932,0.572239,0.008123,0.007796,0.000872,0.005670,0.030367,27246,33.0693,-83.2496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,154,154,WHITFIELD,0,4216384,1,0.070532,0.660559,36955,1040,...,0.034745,0.749127,0.009552,0.127588,0.001380,0.009796,0.067812,55945,34.8056,-84.9672
155,155,155,WILCOX,0,101176,0,0.182849,0.690566,3294,570,...,0.230419,0.740437,0.002429,0.007286,0.000607,0.003643,0.015179,4770,31.9729,-83.4323
156,156,156,WILKES,0,142526,0,0.206583,0.703740,5024,1147,...,0.344944,0.605494,0.004976,0.004379,0.001393,0.005772,0.033041,7139,33.7819,-82.7432
157,157,157,WILKINSON,0,92444,0,0.163246,0.711561,4776,1151,...,0.383585,0.581449,0.001675,0.002094,0.001466,0.003769,0.025963,6712,32.8024,-83.1712
158,158,158,WORTH,0,230358,0,0.114777,0.645210,9322,1555,...,0.212186,0.746514,0.002145,0.004398,0.000536,0.005149,0.029071,14448,31.5515,-83.8509

In [4]:
df = df[['latitude','longitude']]
df

     latitude  longitude
0     31.7492   -82.2889
1     31.2971   -82.8800
2     31.5537   -82.4527
3     31.3262   -84.4447
4     33.0693   -83.2496
..        ...        ...
154   34.8056   -84.9672
155   31.9729   -83.4323
156   33.7819   -82.7432
157   32.8024   -83.1712
158   31.5515   -83.8509

[159 rows x 2 columns]

In [5]:

# Haversine formula to calculate the distance
def haversine(lat1, lon1, lat2, lon2):
    # Radius of Earth in kilometers
    R = 6371.0
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    return c

# Create an empty DataFrame for the distance matrix
distance_matrix = pd.DataFrame(index=df.index, columns=df.index)

# Calculate the distance between each pair of coordinates
for i, county1 in df.iterrows():
    for j, county2 in df.iterrows():
        lat1, lon1 = county1['latitude'], county1['longitude']
        lat2, lon2 = county2['latitude'], county2['longitude']
        distance_matrix.loc[i, j] = haversine(lat1, lon1, lat2, lon2)

# Convert the matrix to float
distance_matrix = distance_matrix.astype(float)

# View the distance matrix
print(distance_matrix)

          0         1         2         3         4         5         6    \
0    0.000000  0.011815  0.004191  0.032907  0.027041  0.048781  0.044378
1    0.011815  0.000000  0.007782  0.023337  0.031409  0.054120  0.048620
2    0.004191  0.007782  0.000000  0.029927  0.028946  0.051216  0.046418
3    0.032907  0.023337  0.029927  0.000000  0.035172  0.054645  0.047774
4    0.027041  0.031409  0.028946  0.035172  0.000000  0.022714  0.017476
..        ...       ...       ...       ...       ...       ...       ...
154  0.066121  0.068420  0.067599  0.061206  0.039202  0.022544  0.022965
155  0.017393  0.014369  0.016274  0.018805  0.019324  0.041574  0.035499
156  0.036098  0.043415  0.039123  0.049632  0.014460  0.014786  0.014523
157  0.022525  0.026623  0.024241  0.031915  0.004798  0.027497  0.022231
158  0.023462  0.015126  0.020795  0.009677  0.027936  0.049191  0.042664

          7         8         9    ...       149       150       151  \
0    0.057279  0.013827  0.016252  ...  0.022572  0.006517  0.033920
1    0.058834  0.009533  0.005227  ...  0.029215  0.015017  0.028059
2    0.058466  0.011960  0.012546  ...  0.025224  0.007971  0.032294
3    0.051146  0.019719  0.018142  ...  0.037632  0.037847  0.012676
4    0.030821  0.022859  0.031300  ...  0.006864  0.032988  0.026173
..        ...       ...       ...  ...       ...       ...       ...
154  0.010078  0.058949  0.066639  ...  0.044904  0.072179  0.048530
155  0.044566  0.004867  0.012531  ...  0.019757  0.023661  0.016608
156  0.031367  0.035981  0.044318  ...  0.014200  0.040777  0.040232
157  0.034891  0.018211  0.026655  ...  0.006226  0.028636  0.024232
158  0.049074  0.010046  0.010429  ...  0.029239  0.028766  0.013513

          152       153       154       155       156       157       158
0    0.009104  0.054865  0.066121  0.017393  0.036098  0.022525  0.023462
1    0.014497  0.059818  0.068420  0.014369  0.043415  0.026623  0.015126
2    0.010628  0.057198  0.067599  0.016274  0.039123  0.024241  0.020795
3    0.029028  0.058841  0.061206  0.018805  0.049632  0.031915  0.009677
4    0.018324  0.028454  0.039202  0.019324  0.014460  0.004798  0.027936
..        ...       ...       ...       ...       ...       ...       ...
154  0.057162  0.017721  0.000000  0.054262  0.036708  0.043596  0.059088
155  0.010768  0.046887  0.054262  0.000000  0.033149  0.014980  0.009627
156  0.029058  0.020918  0.036708  0.033149  0.000000  0.018200  0.042192
157  0.013650  0.033252  0.043596  0.014980  0.018200  0.000000  0.024030
158  0.019400  0.054037  0.059088  0.009627  0.042192  0.024030  0.000000

[159 rows x 159 columns]

In [8]:
R = 6371.0
distance_matrix = distance_matrix*R
distance_matrix

,0,1,2,3,4,5,6,7,8,9,...,149,150,151,152,153,154,155,156,157,158
0,0.000000,75.274674,26.701265,209.647500,172.277441,310.786106,282.731206,364.924267,88.090637,103.540521,...,143.804276,41.518975,216.103631,58.000109,349.546834,421.254913,110.811403,229.981969,143.509073,149.477343
1,75.274674,0.000000,49.577632,148.680055,200.105342,344.799725,309.760617,374.829216,60.733907,33.303489,...,186.130902,95.671396,178.766689,92.357261,381.102525,435.905220,91.546435,276.594476,169.616528,96.369584
2,26.701265,49.577632,0.000000,190.664001,184.415714,326.299217,295.727474,372.486090,76.199880,79.929541,...,160.702865,50.780216,205.742403,67.708337,364.406107,430.670229,103.680867,249.251846,154.438833,132.487001
3,209.647500,148.680055,190.664001,0.000000,224.078145,348.144738,304.367866,325.849603,125.630921,115.581388,...,239.751518,241.124284,80.757035,184.937582,374.875474,389.941235,119.809547,316.203556,203.330274,61.653679
4,172.277441,200.105342,184.415714,224.078145,0.000000,144.709071,111.339664,196.360847,145.635374,199.414745,...,43.732271,210.167077,166.746136,116.745266,181.281815,249.754703,123.111576,92.125494,30.566507,177.979551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,421.254913,435.905220,430.670229,389.941235,249.754703,143.629224,146.313020,64.207209,375.566748,424.557719,...,286.084075,459.854939,309.184362,364.181717,112.900025,0.000000,345.703606,233.868460,277.751815,376.449529
155,110.811403,91.546435,103.680867,119.809547,123.111576,264.868476,226.164086,283.931727,31.008750,79.832961,...,125.874562,150.744715,105.809070,68.602372,298.714901,345.703606,0.000000,211.192660,95.438783,61.333743
156,229.981969,276.594476,249.251846,316.203556,92.125494,94.204379,92.523758,199.836899,229.232044,282.348676,...,90.467201,259.790027,256.316726,185.125448,133.271672,233.868460,211.192660,0.000000,115.952560,268.805933
157,143.509073,169.616528,154.438833,203.330274,30.566507,175.185830,141.631304,222.288630,116.024427,169.817166,...,39.665202,182.438251,154.379228,86.962025,211.846529,277.751815,95.438783,115.952560,0.000000,153.097877
158,149.477343,96.369584,132.487001,61.653679,177.979551,313.398831,271.811837,312.647616,64.005706,66.442651,...,186.281924,183.267131,86.092490,123.596345,344.272911,376.449529,61.333743,268.805933,153.097877,0.000000

In [9]:
# Optionally save to a CSV file
distance_matrix.to_csv("distance_matrix.csv")

In [10]:
# Function to keep only the top 5 closest neighbors and apply inverse transformation
def transform_distance_matrix(matrix):
    # Create a new matrix to store the transformed values
    transformed_matrix = matrix.copy()
    
    for i in matrix.index:
        # Sort the distances for the current row
        sorted_indices = matrix.loc[i].sort_values().index[:5]  # Get top 5 indices
        for j in matrix.columns:
            if j in sorted_indices:
                # Inverse transformation (set 1 / distance)
                transformed_matrix.loc[i, j] = 1 / matrix.loc[i, j] if matrix.loc[i, j] != 0 else 1
            else:
                # Set all other distances to 0
                transformed_matrix.loc[i, j] = 0
    
    return transformed_matrix

# Transform the distance matrix
transformed_matrix = transform_distance_matrix(distance_matrix)

transformed_matrix

,0,1,2,3,4,5,6,7,8,9,...,149,150,151,152,153,154,155,156,157,158
0,1.000000,0.0,0.037451,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.024085,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,0.000000,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.030027,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,0.037451,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,0.000000,0.0,0.000000,1.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,0.000000,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.032716,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.000000,0.0
155,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.032249,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.000000,0.0
156,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.0
157,0.000000,0.0,0.000000,0.0,0.032716,0.0,0.0,0.0,0.000000,0.000000,...,0.025211,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0
158,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0

In [15]:
transformed_matrix.iloc[:,150]

0      0.024085
1      0.000000
2      0.000000
3      0.000000
4      0.000000
         ...
154    0.000000
155    0.000000
156    0.000000
157    0.000000
158    0.000000
Name: 150, Length: 159, dtype: float64

In [16]:
matrix_array = transformed_matrix.to_numpy()

# Save as a .npy file
np.save("distance_matrix.npy", matrix_array)

# To load the .npy file later
loaded_matrix = np.load("distance_matrix.npy")

# Optional: Convert back to DataFrame if needed
loaded_df = pd.DataFrame(loaded_matrix, index=transformed_matrix.index, columns=transformed_matrix.columns)
loaded_df

,0,1,2,3,4,5,6,7,8,9,...,149,150,151,152,153,154,155,156,157,158
0,1.000000,0.0,0.037451,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.024085,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,0.000000,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.030027,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,0.037451,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,0.000000,0.0,0.000000,1.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,0.000000,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.032716,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.000000,0.0
155,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.032249,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.000000,0.0
156,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.0
157,0.000000,0.0,0.000000,0.0,0.032716,0.0,0.0,0.0,0.000000,0.000000,...,0.025211,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0
158,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0

In [17]:
# Function to get the indices of the top 5 closest neighbors
def get_closest_neighbors_indices(matrix, top_n=5):
    closest_indices = []
    for i in matrix.index:
        # Sort distances for each row and get the indices of the smallest values
        closest = matrix.loc[i].nsmallest(top_n + 1).index.tolist()  # +1 to include self
        closest_indices.append(closest)
    return np.array(closest_indices)

# Extract the closest neighbors' indices
closest_neighbors_indices = get_closest_neighbors_indices(distance_matrix)

# Save as .npy file
np.save("index_matrix.npy", closest_neighbors_indices)

# View the result
print(closest_neighbors_indices)

# To load the file later
loaded_indices = np.load("index_matrix.npy")
loaded_indices

[[  0   2  79 131 150 137]
 [  1  33   9  85  31   2]
 [  2   0 112  79  33   1]
 [  3 100  18  46  99  48]
 [  4  83 116 157  69 149]
 [  5  58  77 126  68  67]
 [  6  77 146  66 107  28]
 [  7  63  27  56 109  32]
 [  8  76 155 133 141  33]
 [  9  36  85   1 136  76]
 [ 10  83  38 110 142 101]
 [ 11 115 142  75  44  86]
 [ 12 112 150  19  62 147]
 [ 13  91 135  36  34  85]
 [ 14  88  24  50  90  53]
 [ 15  53  20  50 123  81]
 [ 16  81 120  80 123  35]
 [ 17  78  74  84 125 101]
 [ 18   3 119 134  48  29]
 [ 19  62  12  23  97 112]
 [ 20  52  15  53 137 131]
 [ 21  70  47  73  37 109]
 [ 22 154 145  40 104  63]
 [ 23 147  19  12  31 112]
 [ 24  14  88  50  97  90]
 [ 25 105  95 127 151  71]
 [ 26  56 145  63  40 154]
 [ 27 111  57   7  32  41]
 [ 28 107  94  77 108   6]
 [ 29 119 117  48  18 127]
 [ 30  55  74  42  59 125]
 [ 31  49 147  85   1  91]
 [ 32  59 109  47  27  42]
 [ 33   1  79   2  76   8]
 [ 34  36 136 135 100 158]
 [ 35  96 120  89 148  61]
 [ 36   9  34 136  85  13]
 [ 37  55  73  98  47  21]
 [ 38 110  10 132 101 144]
 [ 39  45 141 155  87 158]
 [ 40 145  22  26 154 104]
 [ 41  92  57 111  68  27]
 [ 42  59 121  66  30  74]
 [ 43 124  64  99   3 100]
 [ 44 115  11 155 133  86]
 [ 45  39 115  93  75 128]
 [ 46  87   3 134 100 158]
 [ 47 109  59  21  32  37]
 [ 48  99  29  18 124   3]
 [ 49  31  91  85 147   1]
 [ 50  15  14  24 123  53]
 [ 51  72  94 108 156  58]
 [ 52  20 139  82  81 102]
 [ 53 131  15  20 137  14]
 [ 54  60 143 104  92 111]
 [ 55  30  37 125  74 113]
 [ 56  26 114   7  63 109]
 [ 57  41  68  66  27  92]
 [ 58 126  72   5  94  67]
 [ 59  32  42  30  47 109]
 [ 60  54 111 104  41  92]
 [ 61 148  80  96 149  69]
 [ 62  97  19  12 150  90]
 [ 63   7 104 154 111  56]
 [ 64 135  43 100   3  34]
 [ 65 130 103 116 108  69]
 [ 66  42   6  57 146 121]
 [ 67 153 126 118   5 138]
 [ 68  57   5  77  92  41]
 [ 69   4 148 130 116  61]
 [ 70 114  21 109  47  56]
 [ 71 105 140 129  98  25]
 [ 72  58  51  94 126   5]
 [ 73 140  21  37  98  70]
 [ 74  30 125 121  17 106]
 [ 75 110 115  11 142  45]
 [ 76   8 136 141   9  33]
 [ 77   6   5  28  68  94]
 [ 78  17 116 106  83 103]
 [ 79 133   2   0  33 152]
 [ 80  61 149  16  82 148]
 [ 81  16 123  52  20  15]
 [ 82 149 139  52  86  80]
 [ 83  10   4 101  78 116]
 [ 84 101 113 125 144  17]
 [ 85  91   9   1  31  36]
 [ 86 139  82  11  44 152]
 [ 87 134  46 128 158  39]
 [ 88  14  90  97  24 150]
 [ 89 156  35  96 130 148]
 [ 90  88 150  14  97 131]
 [ 91  13  85  49  36   9]
 [ 92  41 153 143  68  57]
 [ 93 122 132 110  45  75]
 [ 94  28  58 108  77  72]
 [ 95 122  25 132 151 105]
 [ 96 148  35  61  89 130]
 [ 97  62  88  90 150  14]
 [ 98 113 140  37  71 144]
 [ 99  48 124   3  43  18]
 [100   3  46  64  34 135]
 [101  84  17  10  83  38]
 [102 152 137 139  79 133]
 [103 107  65 146 116 106]
 [104 154  60  63  22  54]
 [105  25  71  95 129 127]
 [106 121 146  74  78  17]
 [107  28 103 146   6 108]
 [108  28  94 156 107  51]
 [109  47  32 114  70   7]
 [110  75  38  10  93 142]
 [111  27  60  41  63  57]
 [112  12   2 150 147   0]
 [113 125  84 144  98  55]
 [114  70  56 109   7  21]
 [115  11 155  44  75  45]
 [116  78   4 103  65  69]
 [117  29 119 127 151  18]
 [118  67 138 126 153 143]
 [119  29 117  18 134 127]
 [120  35  16  96  80  61]
 [121 106  42  74 146  30]
 [122  95 128  93 151 132]
 [123  81  15  50  16  20]
 [124  99  43  48   3  64]
 [125 113  84  74  55  17]
 [126  58  67   5  72 118]
 [127 151 117  25 119  95]
 [128 122  87 151 134  93]
 [129 144 132  71  95 105]
 [130 148  65 156  69  96]
 [131  53 137   0  20  90]
 [132  93  38 129 122  95]
 [133 152  79   8  44  33]
 [134  87 119 151  18  46]
 [135  64  13  34 100  36]
 [136  76 141 158   9  36]
 [137 102 131 152 139  20]
 [138 143 153 118  67  92]
 [139 102  52  86  82 152]
 [140  73  98  71  37 129]
 [141  39 158 136 155  76]
 [142  11 157  10  75 110]
 [143 138  92  54 153  60]
 [144 113  84 129  38 132]
 [145  40  22  26 154  63]
 [146   6 106 107 121 103]
 [147  31 112  23  12   1]
 [148  96  61 130  69  35]
 [149  82  61  80  69 157]
 [150  90 112  12   0  97]
 [151 127 134 122 128  95]
 [152 102 133 139  79 137]
 [153  67  92 138 143  68]
 [154  22 104 145  63  60]
 [155 115   8  39  44 141]
 [156  89 130 108  51  96]
 [157 142   4 149  11  83]
 [158 141 136  46  87  34]]

array([[  0,   2,  79, 131, 150, 137],
       [  1,  33,   9,  85,  31,   2],
       [  2,   0, 112,  79,  33,   1],
       [  3, 100,  18,  46,  99,  48],
       [  4,  83, 116, 157,  69, 149],
       [  5,  58,  77, 126,  68,  67],
       [  6,  77, 146,  66, 107,  28],
       [  7,  63,  27,  56, 109,  32],
       [  8,  76, 155, 133, 141,  33],
       [  9,  36,  85,   1, 136,  76],
       [ 10,  83,  38, 110, 142, 101],
       [ 11, 115, 142,  75,  44,  86],
       [ 12, 112, 150,  19,  62, 147],
       [ 13,  91, 135,  36,  34,  85],
       [ 14,  88,  24,  50,  90,  53],
       [ 15,  53,  20,  50, 123,  81],
       [ 16,  81, 120,  80, 123,  35],
       [ 17,  78,  74,  84, 125, 101],
       [ 18,   3, 119, 134,  48,  29],
       [ 19,  62,  12,  23,  97, 112],
       [ 20,  52,  15,  53, 137, 131],
       [ 21,  70,  47,  73,  37, 109],
       [ 22, 154, 145,  40, 104,  63],
       [ 23, 147,  19,  12,  31, 112],
       [ 24,  14,  88,  50,  97,  90],
       [ 25, 105,  95, 127, 151,  71],
       [ 26,  56, 145,  63,  40, 154],
       [ 27, 111,  57,   7,  32,  41],
       [ 28, 107,  94,  77, 108,   6],
       [ 29, 119, 117,  48,  18, 127],
       [ 30,  55,  74,  42,  59, 125],
       [ 31,  49, 147,  85,   1,  91],
       [ 32,  59, 109,  47,  27,  42],
       [ 33,   1,  79,   2,  76,   8],
       [ 34,  36, 136, 135, 100, 158],
       [ 35,  96, 120,  89, 148,  61],
       [ 36,   9,  34, 136,  85,  13],
       [ 37,  55,  73,  98,  47,  21],
       [ 38, 110,  10, 132, 101, 144],
       [ 39,  45, 141, 155,  87, 158],
       [ 40, 145,  22,  26, 154, 104],
       [ 41,  92,  57, 111,  68,  27],
       [ 42,  59, 121,  66,  30,  74],
       [ 43, 124,  64,  99,   3, 100],
       [ 44, 115,  11, 155, 133,  86],
       [ 45,  39, 115,  93,  75, 128],
       [ 46,  87,   3, 134, 100, 158],
       [ 47, 109,  59,  21,  32,  37],
       [ 48,  99,  29,  18, 124,   3],
       [ 49,  31,  91,  85, 147,   1],
       [ 50,  15,  14,  24, 123,  53],
       [ 51,  72,  94, 108, 156,  58],
       [ 52,  20, 139,  82,  81, 102],
       [ 53, 131,  15,  20, 137,  14],
       [ 54,  60, 143, 104,  92, 111],
       [ 55,  30,  37, 125,  74, 113],
       [ 56,  26, 114,   7,  63, 109],
       [ 57,  41,  68,  66,  27,  92],
       [ 58, 126,  72,   5,  94,  67],
       [ 59,  32,  42,  30,  47, 109],
       [ 60,  54, 111, 104,  41,  92],
       [ 61, 148,  80,  96, 149,  69],
       [ 62,  97,  19,  12, 150,  90],
       [ 63,   7, 104, 154, 111,  56],
       [ 64, 135,  43, 100,   3,  34],
       [ 65, 130, 103, 116, 108,  69],
       [ 66,  42,   6,  57, 146, 121],
       [ 67, 153, 126, 118,   5, 138],
       [ 68,  57,   5,  77,  92,  41],
       [ 69,   4, 148, 130, 116,  61],
       [ 70, 114,  21, 109,  47,  56],
       [ 71, 105, 140, 129,  98,  25],
       [ 72,  58,  51,  94, 126,   5],
       [ 73, 140,  21,  37,  98,  70],
       [ 74,  30, 125, 121,  17, 106],
       [ 75, 110, 115,  11, 142,  45],
       [ 76,   8, 136, 141,   9,  33],
       [ 77,   6,   5,  28,  68,  94],
       [ 78,  17, 116, 106,  83, 103],
       [ 79, 133,   2,   0,  33, 152],
       [ 80,  61, 149,  16,  82, 148],
       [ 81,  16, 123,  52,  20,  15],
       [ 82, 149, 139,  52,  86,  80],
       [ 83,  10,   4, 101,  78, 116],
       [ 84, 101, 113, 125, 144,  17],
       [ 85,  91,   9,   1,  31,  36],
       [ 86, 139,  82,  11,  44, 152],
       [ 87, 134,  46, 128, 158,  39],
       [ 88,  14,  90,  97,  24, 150],
       [ 89, 156,  35,  96, 130, 148],
       [ 90,  88, 150,  14,  97, 131],
       [ 91,  13,  85,  49,  36,   9],
       [ 92,  41, 153, 143,  68,  57],
       [ 93, 122, 132, 110,  45,  75],
       [ 94,  28,  58, 108,  77,  72],
       [ 95, 122,  25, 132, 151, 105],
       [ 96, 148,  35,  61,  89, 130],
       [ 97,  62,  88,  90, 150,  14],
       [ 98, 113, 140,  37,  71, 144],
       [ 99,  48, 124,   3,  43,  18],
       [100,   3,  46,  64,  34, 135],
       [101,  84,  17,  10,  83,  38],
       [102, 152, 137, 139,  79, 133],
       [103, 107,  65, 146, 116, 106],
       [104, 154,  60,  63,  22,  54],
       [105,  25,  71,  95, 129, 127],
       [106, 121, 146,  74,  78,  17],
       [107,  28, 103, 146,   6, 108],
       [108,  28,  94, 156, 107,  51],
       [109,  47,  32, 114,  70,   7],
       [110,  75,  38,  10,  93, 142],
       [111,  27,  60,  41,  63,  57],
       [112,  12,   2, 150, 147,   0],
       [113, 125,  84, 144,  98,  55],
       [114,  70,  56, 109,   7,  21],
       [115,  11, 155,  44,  75,  45],
       [116,  78,   4, 103,  65,  69],
       [117,  29, 119, 127, 151,  18],
       [118,  67, 138, 126, 153, 143],
       [119,  29, 117,  18, 134, 127],
       [120,  35,  16,  96,  80,  61],
       [121, 106,  42,  74, 146,  30],
       [122,  95, 128,  93, 151, 132],
       [123,  81,  15,  50,  16,  20],
       [124,  99,  43,  48,   3,  64],
       [125, 113,  84,  74,  55,  17],
       [126,  58,  67,   5,  72, 118],
       [127, 151, 117,  25, 119,  95],
       [128, 122,  87, 151, 134,  93],
       [129, 144, 132,  71,  95, 105],
       [130, 148,  65, 156,  69,  96],
       [131,  53, 137,   0,  20,  90],
       [132,  93,  38, 129, 122,  95],
       [133, 152,  79,   8,  44,  33],
       [134,  87, 119, 151,  18,  46],
       [135,  64,  13,  34, 100,  36],
       [136,  76, 141, 158,   9,  36],
       [137, 102, 131, 152, 139,  20],
       [138, 143, 153, 118,  67,  92],
       [139, 102,  52,  86,  82, 152],
       [140,  73,  98,  71,  37, 129],
       [141,  39, 158, 136, 155,  76],
       [142,  11, 157,  10,  75, 110],
       [143, 138,  92,  54, 153,  60],
       [144, 113,  84, 129,  38, 132],
       [145,  40,  22,  26, 154,  63],
       [146,   6, 106, 107, 121, 103],
       [147,  31, 112,  23,  12,   1],
       [148,  96,  61, 130,  69,  35],
       [149,  82,  61,  80,  69, 157],
       [150,  90, 112,  12,   0,  97],
       [151, 127, 134, 122, 128,  95],
       [152, 102, 133, 139,  79, 137],
       [153,  67,  92, 138, 143,  68],
       [154,  22, 104, 145,  63,  60],
       [155, 115,   8,  39,  44, 141],
       [156,  89, 130, 108,  51,  96],
       [157, 142,   4, 149,  11,  83],
       [158, 141, 136,  46,  87,  34]])

In [18]:
loaded_indices.shape

(159, 6)